# Generated by Django 4.0.1 on 2022-05-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_remedio', models.CharField(max_length=20, verbose_name='Id remedio')),
                ('nombreRemedio', models.CharField(max_length=50, verbose_name='Nombre remedio')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio remedio')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca remedio')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripcion remedio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
